-- liquibase formatted sql

-- changeset xing:1647841007332-1
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'articles';
CREATE TABLE "articles" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" VARCHAR NOT NULL, "authored" TIMESTAMP WITHOUT TIME ZONE NOT NULL, CONSTRAINT "Article_pkey" PRIMARY KEY ("id"));
-- rollback drop table articles cascade;

-- changeset xing:1647841007332-2
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'comments';
CREATE TABLE "comments" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "comment" VARCHAR NOT NULL, "article_id" BIGINT NOT NULL, CONSTRAINT "comment_pkey" PRIMARY KEY ("id"));
ALTER TABLE "comments" ADD CONSTRAINT "comment_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- rollback drop table comments;

--changeset xing:sample-data
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from articles
INSERT INTO "articles" ("id", "title", "authored") VALUES (1,	'Liquibase is awesome',	'2022-03-20 22:49:10.988446'),(2,	'I love Spring',	'2022-03-20 22:53:27.667624');
INSERT INTO "comments" ("id", "comment", "article_id") VALUES (1,	'First Comment!',	1),(2,	'Second!',	1);
-- rollback truncate articles, comments;



