-- liquibase formatted sql

-- changeset xing:1647841007332-1
CREATE TABLE "articles" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" VARCHAR NOT NULL, "authored" TIMESTAMP WITHOUT TIME ZONE NOT NULL, CONSTRAINT "Article_pkey" PRIMARY KEY ("id"));

-- changeset xing:1647841007332-2
CREATE TABLE "comments" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "comment" VARCHAR NOT NULL, "article_id" BIGINT NOT NULL, CONSTRAINT "comment_pkey" PRIMARY KEY ("id"));

-- changeset xing:1647841007332-3
ALTER TABLE "comments" ADD CONSTRAINT "comment_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

